### ISSUE TITLE
Question regarding emulated_hue configuration

### ISSUE THREAD

**Issue by chownsauce** [geekofweek/homeassistant#14]
I wanted to see why you chose to use the abbreviated names for each of these and why is "Remote" part of it? I can't find anywhere else you are referencing these in your yaml files. Thank you!

    switch.fireplace:
      hidden: false
      name: "Remote FRPLC"
    light.hallway_light:
      hidden: false
      name: "Remote HLLWY"
    light.living_room_lights:
      hidden: false
      name: "Remote LVNGRM"
    light.dining_room_lights:
      hidden: false
      name: "Remote DNGRM"
    light.bedroom_lights:
      hidden: false
      name: "Remote BDRM"
    light.kitchen_lights:
      hidden: false
      name: "Remote KTCHN"
    light.bathroom_lights:
      hidden: false
      name: "Remote BTH"

**Comment by geekofweek** [comment]
Good question, because I use it via emulated hue for the Logitech Harmony.  It was a way for me to identify it at the time and assign it to the harmony controllers easier.  Since the Hue natively supports the Amazon Echo it got confusing which was the emulated Hue and which was the actual Hue.  Making my life easier in identify things that was really about it.

**Comment by chownsauce** [comment]
Thanks! Your configuration is very nice and I'm working to implement as much of it as I can for my own needs. Appreciate you sharing it!
