### ISSUE TITLE
Recommend TI CC2652P based "Sonoff ZBDongle-P" instead of Silabs EFR32MG21 based "Sonoff ZBDongle-E" for Zigbee2MQTT

### ISSUE THREAD

**Issue by Hedda** [geekofweek/homeassistant#23]
https://github.com/geekofweek/homeassistant/blob/master/README.md

| Device  | Quantity | Connection | Home Assistant | Notes |
| ------------- | :---: | ------------- | ------------- | ------------- |
| [SONOFF Zigbee 3.0 USB Dongle Plus-E](https://amzn.to/3oLXD9z) | 1 | USB | [Zigbee2MQTT](https://www.home-assistant.io/integrations/mqtt/) | Used to control all Zigbee smart bulbs and Blinds.  ZHA was becoming un-reliable for me so switched to Zigbee2MQTT |

Recommend use TI CC2652P based "[Sonoff ZBDongle-P](https://community.home-assistant.io/t/iteads-sonoff-zigbee-3-0-usb-dongle-plus-based-on-texas-instruments-cc2652p-20dbm-radio-mcu-now-sold-for-14-99/340705)" instead of Silabs EFR32MG21 based "[Sonoff ZBDongle-E](https://community.home-assistant.io/t/itead-s-sonoff-zigbee-3-0-usb-dongle-plus-v2-model-zbdongle-e-based-on-silicon-labs-efr32mg21-20dbm-radio-soc-mcu/442695)" for Zigbee2MQTT:

https://www.zigbee2mqtt.io/guide/adapters/#recommended

verses 

https://www.zigbee2mqtt.io/guide/adapters/#experimental

Reason is that the ezsp adapter code in the zigbee-herdsman library which Zigbee2MQTT does not quite yet have feature-parity with its zstack adapter code, and most notable the ezsp adapter code is missing full backup and restore support -> https://github.com/Koenkk/zigbee-herdsman/issues/319 preventing restoring backups and migration -> https://www.zigbee2mqtt.io/guide/faq/#how-do-i-migrate-from-one-adapter-to-another

PS: If where to use Home Assistant's ZHA integration then would instead recommend Silicon Labs over Texas Instruments based Zigbee Coordinator -> https://www.home-assistant.io/integrations/zha however that is primarly just because Home Assistant SkyConnect is based on Silabs EFR32MG21 -> https://www.home-assistant.io/skyconnectDevice	Quantity	Connection	Home Assistant	Notes
[SONOFF Zigbee 3.0 USB Dongle Plus-E](https://amzn.to/3oLXD9z)	1	USB	[Zigbee2MQTT](https://www.home-assistant.io/integrations/mqtt/)	Used to control all Zigbee smart bulbs and Blinds. ZHA was becoming un-reliable for me so switched to Zigbee2MQTT

PPS: Regardless of Zigbee gateway solution I highly recommend to read and follow all the tips here -> https://community.home-assistant.io/t/zigbee-networks-how-to-guide-for-avoiding-interference-and-optimize-for-getting-better-range-coverage/515752

**Comment by geekofweek** [comment]
It hasn't caused me any issues and has worked well for some time now.  Originally it was purchased for ZHA prior to the SkyConnect being released, once that was release I picked up a SkyConnect so I do own one of those.  I used the SkyConnect for a while with ZHA but had some stability issues so I migrated back to the SONOFF.  Still was having stability issues and migrated to Zigbee2MQTT.  Turns out I had some overly chatty devices causing the problem (Zonoff power monitoring switches).  I don't think I would have found the problem without Z2M and it works well enough that it hasn't been worth the effort to migrate it all back to ZHA as that is a serious pain.  

I'm fairly well versed in the in and outs of Zigbee and radio interference, etc.  but I appreciate you taking the time to comment.

**Comment by Hedda** [comment]
FYI, check out this thread for unofficial method on how to migrate from ZBDongle-E to ZBDongle-P for thoee using Zigbee2MQTT -> https://github.com/Koenkk/zigbee2mqtt/discussions/16478

Tip is then to reflash the ZBDongle-E with Zigbee Router firmware to repurpose it as a dedicated Zigbee repeater/extender by powering it via a USB-charger in order to make it into a stand-alone product -> https://sonoff.tech/wp-content/uploads/2022/11/SONOFF-Zigbee-3.0-USB-dongle-plus-firmware-flashing-.pdf
